FROM tensorflow/tensorflow:2.0.0b1-py3

# TODO: upgrade python 3.6 to 3.7
# TODO: make mysql run on startup - systemctl ?
# TODO: update-alternatives: using /etc/mysql/mysql.cnf to provide /etc/mysql/my.cnf (my.cnf) in auto mode
RUN apt-get update && apt-get install --yes tree libhdf5-dev python3-all-dev mysql-server && \
    update-rc.d mysql defaults && \
    pip3 install --upgrade pip setuptools && \
    pip3 install -r requirements.txt

# get argument from docker compose file
ARG version
ARG db_ip
ARG model_dir
ARG model_builder_class

ENV FLASK_APP reviews.py
ENV VERSION $version
ENV MODEL_BUILDER_CLASS $model_builder_class
ENV DB_IP $db_ip

RUN adduser --disabled-password reviews

# TODO: put this back in when we figure out how to start mysql automatically
#WORKDIR /home/reviews

# TODO: put these back when we figure out how to start mysql automatically
# RUN chown -R reviews:reviews ./
# USER reviews

# re-install gcc for our pip install
COPY requirements.txt ./

# TODO: update this script to run wgsi server instead for Production
EXPOSE 5000
ENTRYPOINT ["/etc/init.d/mysql start && ./run_service.sh"]
