FROM tensorflow/tensorflow:2.0.0b1-py3

RUN adduser --disabled-password reviews

WORKDIR /home/reviews

# re-install gcc for our pip install
COPY requirements.txt ./
RUN apt-get update && \
    apt-get install  --yes libhdf5-dev python3-all-dev python-mysqldb libmysqlclient-dev && \
    pip3 install --upgrade pip setuptools && \
    pip3 install virtualenv && \
    pip3 install -r requirements.txt && \
    mkdir models

# get argument from docker compose file
ARG version
ARG gcp_project_id
ARG gcp_bucket_name
ARG model_builder_class
ARG google_application_credentials
ARG db_ip

ENV FLASK_APP reviews.py
ENV VERSION $version
ENV PROJECT_ID $gcp_project_id
ENV BUCKET_NAME $gcp_bucket_name
ENV GOOGLE_APPLICATION_CREDENTIALS $google_application_credentials
ENV MODEL_BUILDER_CLASS $model_builder_class
ENV DB_IP $db_ip


COPY util ./util
COPY templates ./templates
COPY credentials ./credentials
COPY reviews.py config.py run_service.sh ./
RUN chmod +x run_service.sh

RUN chown -R reviews:reviews ./

USER reviews

# TODO: update this script to run wgsi server instead for Production
EXPOSE 5000
# run flask server and bind to 0.0.0.0 so port can be mapped
# TODO: change this to run flask directly
#ENTRYPOINT ["/usr/local/bin/flask run --host 0.0.0.0"]
ENTRYPOINT ["./run_service.sh"]
