FROM tensorflow/tensorflow:2.0.0b1-py3

# create user and add to sudoers
RUN adduser --disabled-password reviews
WORKDIR /home/reviews

# TODO: upgrade python 3.6 to 3.7
# TODO: make mysql run on startup - systemctl ?
# TODO: update-alternatives: using /etc/mysql/mysql.cnf to provide /etc/mysql/my.cnf (my.cnf) in auto mode
# re-install gcc for our pip install
RUN apt-get update && \
    apt-get install --yes tree libhdf5-dev python3-all-dev mysql-server vim less && \
    update-rc.d mysql defaults


COPY requirements.txt ./
RUN pip3 install --upgrade pip setuptools && \
    pip3 install -r ./requirements.txt

# TODO: and nltk download

# get argument from docker compose file
ARG version
ARG db_ip
ARG model_dir
ARG sqlite_dir
ARG db_type

ENV FLASK_APP reviews.py
ENV VERSION $version
ENV SQLITE_DIR $sqlite_dir
ENV DB_TYPE $db_type
ENV DB_IP $db_ip


RUN chown -R reviews:reviews ./ && usermod -aG sudo reviews
# TODO: put these back when we figure out how to start mysql automatically
# USER reviews


# TODO: update this script to run wgsi server instead for Production
EXPOSE 5000
ENTRYPOINT ["./run_service.sh"]
