FROM tensorflow/tensorflow:2.0.0b1-py3

RUN adduser --disabled-password reviews
WORKDIR /home/reviews

# re-install gcc for our pip install
RUN apt-get update && \
    apt-get install --yes tree libhdf5-dev python3-all-dev mysql-server vim less && \
    update-rc.d mysql defaults

COPY requirements.txt ./
RUN pip3 install --upgrade pip setuptools && \
    pip3 install -r ./requirements.txt


# get argument from docker compose file
ARG version
ARG db_ip
ARG model_dir
ARG sqlite_dir
ARG db_type

ENV FLASK_APP reviews.py
ENV VERSION $version
ENV SQLITE_DIR $sqlite_dir
ENV DB_TYPE $db_type
ENV DB_IP $db_ip

COPY util ./util
COPY templates ./templates
COPY reviews.py config.py run_service.sh ./
RUN chmod +x run_service.sh

RUN chown -R reviews:reviews ./

USER reviews

# TODO: update this script to run wgsi server instead for Production
EXPOSE 5000
# run flask server and bind to 0.0.0.0 so port can be mapped
ENTRYPOINT ["./run_service.sh"]
